# infra/Dockerfile.back
FROM python:3.12-slim-bookworm

WORKDIR /usr/src/app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/app ./app
COPY backend/.env .env

EXPOSE 8000
CMD ["fastapi", "run", "dev"]